# Moneytrend Crawling

In [2]:
import FinanceDataReader as fdr
import pandas as pd
from bs4 import BeautifulSoup
import datetime as dt
from datetime import datetime,timedelta
from urllib.request import urlopen
import sqlalchemy 
import pymysql
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

In [ ]:
def get_a(until_date='1995-12-27'):
    
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['KPI200','거래량'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [].'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인'.'기관']

    # count mask
    mask = [0,1,2.3]
    
    for i in range(1,700):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        tr = body.find_all('tr')
        for tr in trs:
            date = r.find('td',{'class':'date2'})
            count = 0
            if count == 0:
                date_ = td.text.strip().replace('.','-')
                        
                    if not date_ in date_list :
                        date_list.append(date_)
                                    
                        #마지막 페이지인 경우
                        else:
                            print(str(i-1) + '번째 페이지에서 크롤링 종료')
                            df = pd.DataFrame(dictionary,index = date_list)
                            df = df.sort_index()
                            #df.거래량 = df.거래량.str.replace(',','')
                            df.to_excel(path, encoding='utf-8')

                            return df

                        elif count in mask:
                            temp = int(count/5)
                            dictionary[name_list[temp]].append(td.text.strip())
                                
                    #print(count)
                    count += 1
            
            # 누락된 값을 발견하면 (펀드 자료에 누락된 값이 존재함)
            if len(dictionary['KPI200']) != len(dictionary['거래량']):
                print(str(i)+ '번째 페이지에서 누락된 값 발생')
                print('누락된 데이터를 제거합니다')
                    
                date_list.pop(-1)
                dictionary['KPI200'].pop(-1)
                dictionary['거래량'].pop(-1)
                
        print(str(i) + '번째 페이지 크롤링 완료')

In [13]:
def get_a(until_date='1995-12-27'):
    #until_date = input("날짜를 입력하세요 sample: '2019-01-10':")
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['개인','외국인','기관'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [],'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인','기관']

    # count mask
    mask = [0,1,2.3]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        trs = body.find_all('tr')
        for tr in trs:
            print(tr)
get_a()

<tr class="udline">
<th class="noln" rowspan="2">날짜</th>
<th rowspan="2">개인</th>
<th rowspan="2">외국인</th>
<th rowspan="2">기관계</th>
<th class="eb" colspan="6">기관</th>
<th rowspan="2">기타법인</th>
</tr>
<tr class="udline">
<th class="sub">금융투자</th>
<th class="sub">보험</th>
<th class="sub">투신<br/>(사모)</th>
<th class="sub">은행</th>
<th class="sub">기타금융기관</th>
<th class="sub">연기금등</th>
</tr>
<tr>
<td class="blank_07" colspan="11"></td>
</tr>
<tr>
<td class="date2">19.03.11</td>
<td class="rate_up3">894</td>
<td class="rate_down3">-1,793</td>
<td class="rate_up3">166</td>
<td class="rate_up3">751</td>
<td class="rate_up3">292</td>
<td class="rate_down3">-852</td>
<td class="rate_up3">8</td>
<td class="rate_up3">6</td>
<td class="rate_down3">-39</td>
<td class="rate_up3">733</td>
</tr>
<tr>
<td class="date2">19.03.08</td>
<td class="rate_up3">2,932</td>
<td class="rate_down3">-1,739</td>
<td class="rate_down3">-1,274</td>
<td class="rate_down3">-342</td>
<td class="rate_up3">72</td>
<td class="rate_down3">-1,059</td>
<td class="rate_up3">14</td>
<td class="rate_down3">-18</td>
<td class="rate_up3">58</td>
<td class="rate_up3">81</td>
</tr>
<tr>
<td class="date2">19.03.07</td>
<td class="rate_up3">1,108</td>
<td class="rate_up3">4</td>
<td class="rate_down3">-1,130</td>
<td class="rate_up3">380</td>
<td class="rate_down3">-229</td>
<td class="rate_down3">-848</td>
<td class="rate_up3">20</td>
<td class="rate_down3">-14</td>
<td class="rate_down3">-439</td>
<td class="rate_up3">18</td>
</tr>
<tr>
<td class="date2">19.03.06</td>
<td class="rate_up3">654</td>
<td class="rate_up3">60</td>
<td class="rate_down3">-532</td>
<td class="rate_up3">41</td>
<td class="rate_up3">137</td>
<td class="rate_up3">231</td>
<td class="rate_down3">-34</td>
<td class="rate_up3">10</td>
<td class="rate_down3">-917</td>
<td class="rate_down3">-182</td>
</tr>
<tr>
<td class="date2">19.03.05</td>
<td class="rate_up3">2,444</td>
<td class="rate_down3">-1,570</td>
<td class="rate_down3">-919</td>
<td class="rate_up3">1,068</td>
<td class="rate_down3">-135</td>
<td class="rate_down3">-1,100</td>
<td class="rate_down3">-14</td>
<td class="rate_down3">-20</td>
<td class="rate_down3">-719</td>
<td class="rate_up3">46</td>
</tr>
<tr>
<td class="blank_08" colspan="11"></td>
</tr>
<tr>
<td class="division_line" colspan="11"></td>
</tr>
<tr>
<td class="blank_08" colspan="11"></td>
</tr>
<tr>
<td class="date2">19.03.04</td>
<td class="rate_up3">403</td>
<td class="rate_down3">-1,320</td>
<td class="rate_up3">767</td>
<td class="rate_up3">2,942</td>
<td class="rate_down3">-565</td>
<td class="rate_down3">-1,270</td>
<td class="rate_up3">6</td>
<td class="rate_up3">1</td>
<td class="rate_down3">-348</td>
<td class="rate_up3">149</td>
</tr>
<tr>
<td class="date2">19.02.28</td>
<td class="rate_down3">-618</td>
<td class="rate_down3">-2,536</td>
<td class="rate_up3">3,169</td>
<td class="rate_up3">3,873</td>
<td class="rate_down3">-441</td>
<td class="rate_down3">-512</td>
<td class="rate_up3">78</td>
<td class="rate_down3">-25</td>
<td class="rate_up3">196</td>
<td class="rate_down3">-15</td>
</tr>
<tr>
<td class="date2">19.02.27</td>
<td class="rate_down3">-1,116</td>
<td class="rate_down3">-573</td>
<td class="rate_up3">1,519</td>
<td class="rate_up3">1,792</td>
<td class="rate_down3">-148</td>
<td class="rate_down3">-675</td>
<td class="rate_down3">-16</td>
<td class="rate_up3">11</td>
<td class="rate_up3">556</td>
<td class="rate_up3">170</td>
</tr>
<tr>
<td class="date2">19.02.26</td>
<td class="rate_down3">-299</td>
<td class="rate_up3">526</td>
<td class="rate_down3">-111</td>
<td class="rate_up3">12</td>
<td class="rate_down3">-114</td>
<td class="rate_down3">-257</td>
<td class="rate_up3">20</td>
<td class="rate_noc3">0</td>
<td class="rate_up3">227</td>
<td class="rate_down3">-115</td>
</tr>
<tr>
<td class="date2">19.02.25</td>
<td class="rate_up3">91</td>
<td class="rate_down3">-796</td>
<td class="rate_up3">803</td>
<td class="rate_up3">1,468</td>
<td class="rate_down3">-289</td>
<td class="rate_down3">-156</td>
<td class="rate_down3">-21</td>
<td class="rate_down3">-6</td>
<td class="rate_down3">-194</td>
<td class="rate_down3">-98</td>
</tr>
<tr>
<td class="blank_09" colspan="11"></td>
</tr>
<tr>
<td class="division_line_1" colspan="11"></td>
</tr>
<tr>
<td class="on">
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=1">1</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=2">2</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=3">3</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=4">4</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=5">5</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=6">6</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=7">7</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=8">8</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=9">9</a>
</td>
<td>
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=10">10</a>
</td>
<td class="pgR">
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=11">
				다음<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
</a>
</td>
<td class="pgRR">
<a href="/sise/investorDealTrendDay.nhn?bizdate=2020601&amp;sosok=&amp;page=351">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
</td>
</tr>

In [16]:
def get_a(until_date='1995-12-27'):
    #until_date = input("날짜를 입력하세요 sample: '2019-01-10':")
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['개인','외국인','기관'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [],'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인','기관']

    # count mask
    mask = [0,1,2.3]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        trs = body.find_all('tr')
        for tr in trs:
            if tr.find('td',{'class':'date2'}):
                print(tr.find('td',{'class':'date2'}))
get_a()

<td class="date2">19.03.11</td>
<td class="date2">19.03.08</td>
<td class="date2">19.03.07</td>
<td class="date2">19.03.06</td>
<td class="date2">19.03.05</td>
<td class="date2">19.03.04</td>
<td class="date2">19.02.28</td>
<td class="date2">19.02.27</td>
<td class="date2">19.02.26</td>
<td class="date2">19.02.25</td>

In [17]:
def get_a(until_date='1995-12-27'):
    #until_date = input("날짜를 입력하세요 sample: '2019-01-10':")
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['개인','외국인','기관'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [],'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인','기관']

    # count mask
    mask = [0,1,2.3]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        trs = body.find_all('tr')
        for tr in trs:
            if tr.find('td',{'class':'rate_up3'}):
                print(tr.find('td',{'class':'rate_up3'}))
get_a()

<td class="rate_up3">894</td>
<td class="rate_up3">2,932</td>
<td class="rate_up3">1,108</td>
<td class="rate_up3">654</td>
<td class="rate_up3">2,444</td>
<td class="rate_up3">403</td>
<td class="rate_up3">3,169</td>
<td class="rate_up3">1,519</td>
<td class="rate_up3">526</td>
<td class="rate_up3">91</td>

In [83]:
def get_a(until_date='1995-12-27'):
    
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['개인','외국인','기관'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [],'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인','기관']

    # count mask
    mask = [0,1,2.3]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td',{'class':'date2'})
            for td in tds:
                if not td.text.strip ==0:
                    print(td)
get_a()

<td class="date2">19.03.11</td>
<td class="date2">19.03.08</td>
<td class="date2">19.03.07</td>
<td class="date2">19.03.06</td>
<td class="date2">19.03.05</td>
<td class="date2">19.03.04</td>
<td class="date2">19.02.28</td>
<td class="date2">19.02.27</td>
<td class="date2">19.02.26</td>
<td class="date2">19.02.25</td>

In [19]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형 펀드': [],
                  '혼합형 펀드': [],
                  '채권형 펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            print(tr)
get_money_trend()

<tr class="udline">
<th rowspan="2">날짜</th>
<th colspan="2" rowspan="2">고객예탁금</th>
<th colspan="2" rowspan="2">신용잔고</th>
<th class="eb" colspan="6">펀드</th>
</tr>
<tr class="udline">
<th class="sub" colspan="2">주식형</th>
<th class="sub" colspan="2">혼합형</th>
<th class="sub" colspan="2">채권형</th>
</tr>
<tr><td class="blank_07" colspan="11"></td></tr>
<tr>
<td class="date">19.03.07</td>
<td class="rate_down">247,796</td>
<td class="rate_down">127</td>
<td class="rate_up">102,702</td>
<td class="rate_up">638</td>
<td class="rate_down">868,665</td>
<td class="rate_down">3,663</td>
<td class="rate_down">275,411</td>
<td class="rate_down">73</td>
<td class="rate_up">1,073,283</td>
<td class="rate_up">1,756</td>
</tr>
<tr>
<td class="date">19.03.06</td>
<td class="rate_down">247,923</td>
<td class="rate_down">2,273</td>
<td class="rate_down">102,065</td>
<td class="rate_down">1,039</td>
<td class="rate_down">872,328</td>
<td class="rate_down">2,354</td>
<td class="rate_up">275,484</td>
<td class="rate_up">252</td>
<td class="rate_up">1,071,527</td>
<td class="rate_up">42</td>
</tr>
<tr>
<td class="date">19.03.05</td>
<td class="rate_down">250,195</td>
<td class="rate_down">11,328</td>
<td class="rate_down">103,104</td>
<td class="rate_down">1,547</td>
<td class="rate_down">874,682</td>
<td class="rate_down">892</td>
<td class="rate_up">275,232</td>
<td class="rate_up">133</td>
<td class="rate_up">1,071,485</td>
<td class="rate_up">2,625</td>
</tr>
<tr>
<td class="date">19.03.04</td>
<td class="rate_up">261,523</td>
<td class="rate_up">6,523</td>
<td class="rate_up">104,651</td>
<td class="rate_up">121</td>
<td class="rate_down">875,574</td>
<td class="rate_down">1,063</td>
<td class="rate_up">275,099</td>
<td class="rate_up">31</td>
<td class="rate_up">1,068,860</td>
<td class="rate_up">542</td>
</tr>
<tr>
<td class="date">19.02.28</td>
<td class="rate_down">255,000</td>
<td class="rate_down">1,436</td>
<td class="rate_up">104,531</td>
<td class="rate_up">231</td>
<td class="rate_down">876,637</td>
<td class="rate_down">5,948</td>
<td class="rate_down">275,068</td>
<td class="rate_down">54</td>
<td class="rate_up">1,068,318</td>
<td class="rate_up">7,119</td>
</tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr><td class="division_line" colspan="11"></td></tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr>
<td class="date">19.02.27</td>
<td class="rate_down">256,436</td>
<td class="rate_down">12</td>
<td class="rate_up">104,300</td>
<td class="rate_up">133</td>
<td class="rate_up">882,585</td>
<td class="rate_up">568</td>
<td class="rate_up">275,122</td>
<td class="rate_up">624</td>
<td class="rate_down">1,061,199</td>
<td class="rate_down">1,356</td>
</tr>
<tr>
<td class="date">19.02.26</td>
<td class="rate_up">256,448</td>
<td class="rate_up">7,195</td>
<td class="rate_up">104,167</td>
<td class="rate_up">133</td>
<td class="rate_down">882,017</td>
<td class="rate_down">1,929</td>
<td class="rate_up">274,498</td>
<td class="rate_up">35</td>
<td class="rate_up">1,062,555</td>
<td class="rate_up">2,645</td>
</tr>
<tr>
<td class="date">19.02.25</td>
<td class="rate_up">249,253</td>
<td class="rate_up">3,581</td>
<td class="rate_up">104,034</td>
<td class="rate_up">333</td>
<td class="rate_down">883,946</td>
<td class="rate_down">918</td>
<td class="rate_down">274,463</td>
<td class="rate_down">338</td>
<td class="rate_up">1,059,910</td>
<td class="rate_up">1,142</td>
</tr>
<tr>
<td class="date">19.02.22</td>
<td class="rate_up">245,671</td>
<td class="rate_up">419</td>
<td class="rate_up">103,701</td>
<td class="rate_up">156</td>
<td class="rate_down">884,864</td>
<td class="rate_down">429</td>
<td class="rate_down">274,801</td>
<td class="rate_down">210</td>
<td class="rate_down">1,058,768</td>
<td class="rate_down">850</td>
</tr>
<tr>
<td class="date">19.02.21</td>
<td class="rate_down">245,252</td>
<td class="rate_down">5,593</td>
<td class="rate_up">103,545</td>
<td class="rate_up">262</td>
<td class="rate_down">885,293</td>
<td class="rate_down">568</td>
<td class="rate_up">275,011</td>
<td class="rate_up">19</td>
<td class="rate_up">1,059,618</td>
<td class="rate_up">2,502</td>
</tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr><td class="division_line" colspan="11"></td></tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr>
<td class="date">19.02.20</td>
<td class="rate_up">250,845</td>
<td class="rate_up">8,001</td>
<td class="rate_down">103,283</td>
<td class="rate_down">64</td>
<td class="rate_up">885,861</td>
<td class="rate_up">2,860</td>
<td class="rate_down">274,992</td>
<td class="rate_down">267</td>
<td class="rate_up">1,057,116</td>
<td class="rate_up">289</td>
</tr>
<tr>
<td class="date">19.02.19</td>
<td class="rate_down">242,844</td>
<td class="rate_down">2,770</td>
<td class="rate_up">103,347</td>
<td class="rate_up">750</td>
<td class="rate_down">883,001</td>
<td class="rate_down">1,772</td>
<td class="rate_down">275,259</td>
<td class="rate_down">326</td>
<td class="rate_up">1,056,827</td>
<td class="rate_up">360</td>
</tr>
<tr>
<td class="date">19.02.18</td>
<td class="rate_up">245,614</td>
<td class="rate_up">2,038</td>
<td class="rate_up">102,596</td>
<td class="rate_up">502</td>
<td class="rate_up">884,773</td>
<td class="rate_up">2,388</td>
<td class="rate_up">275,585</td>
<td class="rate_up">162</td>
<td class="rate_up">1,056,467</td>
<td class="rate_up">191</td>
</tr>
<tr>
<td class="date">19.02.15</td>
<td class="rate_down">243,576</td>
<td class="rate_down">1,583</td>
<td class="rate_up">102,094</td>
<td class="rate_up">292</td>
<td class="rate_down">882,385</td>
<td class="rate_down">1,478</td>
<td class="rate_up">275,423</td>
<td class="rate_up">64</td>
<td class="rate_up">1,056,276</td>
<td class="rate_up">3,710</td>
</tr>
<tr>
<td class="date">19.02.14</td>
<td class="rate_down">245,159</td>
<td class="rate_down">3,828</td>
<td class="rate_up">101,802</td>
<td class="rate_up">432</td>
<td class="rate_up">883,863</td>
<td class="rate_up">1,823</td>
<td class="rate_up">275,359</td>
<td class="rate_up">267</td>
<td class="rate_up">1,052,566</td>
<td class="rate_up">3,144</td>
</tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr><td class="division_line" colspan="11"></td></tr>
<tr><td class="blank_08" colspan="11"></td></tr>
<tr>
<td class="date">19.02.13</td>
<td class="rate_down">248,987</td>
<td class="rate_down">487</td>
<td class="rate_up">101,371</td>
<td class="rate_up">847</td>
<td class="rate_up">882,040</td>
<td class="rate_up">2,589</td>
<td class="rate_down">275,092</td>
<td class="rate_down">80</td>
<td class="rate_up">1,049,422</td>
<td class="rate_up">646</td>
</tr>
<tr>
<td class="date">19.02.12</td>
<td class="rate_down">249,473</td>
<td class="rate_down">12,395</td>
<td class="rate_up">100,523</td>
<td class="rate_up">1,028</td>
<td class="rate_down">879,451</td>
<td class="rate_down">450</td>
<td class="rate_down">275,172</td>
<td class="rate_down">18</td>
<td class="rate_up">1,048,776</td>
<td class="rate_up">1,643</td>
</tr>
<tr>
<td class="date">19.02.11</td>
<td class="rate_up">261,868</td>
<td class="rate_up">11,570</td>
<td class="rate_up">99,495</td>
<td class="rate_up">212</td>
<td class="rate_down">879,901</td>
<td class="rate_down">687</td>
<td class="rate_down">275,190</td>
<td class="rate_down">215</td>
<td class="rate_up">1,047,133</td>
<td class="rate_up">349</td>
</tr>
<tr>
<td class="date">19.02.08</td>
<td class="rate_down">250,298</td>
<td class="rate_down">16,328</td>
<td class="rate_down">99,283</td>
<td class="rate_down">135</td>
<td class="rate_down">880,588</td>
<td class="rate_down">4,247</td>
<td class="rate_down">275,405</td>
<td class="rate_down">53</td>
<td class="rate_up">1,046,784</td>
<td class="rate_up">1,657</td>
</tr>
<tr>
<td class="date">19.02.07</td>
<td class="rate_up">266,626</td>
<td class="rate_up">14,810</td>
<td class="rate_up">99,418</td>
<td class="rate_up">543</td>
<td class="rate_down">884,835</td>
<td class="rate_down">1,084</td>
<td class="rate_up">275,458</td>
<td class="rate_up">91</td>
<td class="rate_up">1,045,127</td>
<td class="rate_up">3,416</td>
</tr>
<tr><td class="blank_09" colspan="11"></td></tr>
<tr><td class="division_line_1" colspan="11"></td></tr>
<tr>
<td class="on">
<a href="/sise/sise_deposit.nhn?&amp;page=1">1</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=2">2</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=3">3</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=4">4</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=5">5</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=6">6</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=7">7</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=8">8</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=9">9</a>
</td>
<td>
<a href="/sise/sise_deposit.nhn?&amp;page=10">10</a>
</td>
<td class="pgR">
<a href="/sise/sise_deposit.nhn?&amp;page=11">
				다음<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
</a>
</td>
<td class="pgRR">
<a href="/sise/sise_deposit.nhn?&amp;page=208">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
</td>
</tr>

In [79]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형 펀드': [],
                  '혼합형 펀드': [],
                  '채권형 펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            print(tds)
get_money_trend()

[]
[]
[<td class="blank_07" colspan="11"></td>]
[<td class="date">19.03.07</td>, <td class="rate_down">247,796</td>, <td class="rate_down">127</td>, <td class="rate_up">102,702</td>, <td class="rate_up">638</td>, <td class="rate_down">868,665</td>, <td class="rate_down">3,663</td>, <td class="rate_down">275,411</td>, <td class="rate_down">73</td>, <td class="rate_up">1,073,283</td>, <td class="rate_up">1,756</td>]
[<td class="date">19.03.06</td>, <td class="rate_down">247,923</td>, <td class="rate_down">2,273</td>, <td class="rate_down">102,065</td>, <td class="rate_down">1,039</td>, <td class="rate_down">872,328</td>, <td class="rate_down">2,354</td>, <td class="rate_up">275,484</td>, <td class="rate_up">252</td>, <td class="rate_up">1,071,527</td>, <td class="rate_up">42</td>]
[<td class="date">19.03.05</td>, <td class="rate_down">250,195</td>, <td class="rate_down">11,328</td>, <td class="rate_down">103,104</td>, <td class="rate_down">1,547</td>, <td class="rate_down">874,682</td>, <td class="rate_down">892</td>, <td class="rate_up">275,232</td>, <td class="rate_up">133</td>, <td class="rate_up">1,071,485</td>, <td class="rate_up">2,625</td>]
[<td class="date">19.03.04</td>, <td class="rate_up">261,523</td>, <td class="rate_up">6,523</td>, <td class="rate_up">104,651</td>, <td class="rate_up">121</td>, <td class="rate_down">875,574</td>, <td class="rate_down">1,063</td>, <td class="rate_up">275,099</td>, <td class="rate_up">31</td>, <td class="rate_up">1,068,860</td>, <td class="rate_up">542</td>]
[<td class="date">19.02.28</td>, <td class="rate_down">255,000</td>, <td class="rate_down">1,436</td>, <td class="rate_up">104,531</td>, <td class="rate_up">231</td>, <td class="rate_down">876,637</td>, <td class="rate_down">5,948</td>, <td class="rate_down">275,068</td>, <td class="rate_down">54</td>, <td class="rate_up">1,068,318</td>, <td class="rate_up">7,119</td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="division_line" colspan="11"></td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="date">19.02.27</td>, <td class="rate_down">256,436</td>, <td class="rate_down">12</td>, <td class="rate_up">104,300</td>, <td class="rate_up">133</td>, <td class="rate_up">882,585</td>, <td class="rate_up">568</td>, <td class="rate_up">275,122</td>, <td class="rate_up">624</td>, <td class="rate_down">1,061,199</td>, <td class="rate_down">1,356</td>]
[<td class="date">19.02.26</td>, <td class="rate_up">256,448</td>, <td class="rate_up">7,195</td>, <td class="rate_up">104,167</td>, <td class="rate_up">133</td>, <td class="rate_down">882,017</td>, <td class="rate_down">1,929</td>, <td class="rate_up">274,498</td>, <td class="rate_up">35</td>, <td class="rate_up">1,062,555</td>, <td class="rate_up">2,645</td>]
[<td class="date">19.02.25</td>, <td class="rate_up">249,253</td>, <td class="rate_up">3,581</td>, <td class="rate_up">104,034</td>, <td class="rate_up">333</td>, <td class="rate_down">883,946</td>, <td class="rate_down">918</td>, <td class="rate_down">274,463</td>, <td class="rate_down">338</td>, <td class="rate_up">1,059,910</td>, <td class="rate_up">1,142</td>]
[<td class="date">19.02.22</td>, <td class="rate_up">245,671</td>, <td class="rate_up">419</td>, <td class="rate_up">103,701</td>, <td class="rate_up">156</td>, <td class="rate_down">884,864</td>, <td class="rate_down">429</td>, <td class="rate_down">274,801</td>, <td class="rate_down">210</td>, <td class="rate_down">1,058,768</td>, <td class="rate_down">850</td>]
[<td class="date">19.02.21</td>, <td class="rate_down">245,252</td>, <td class="rate_down">5,593</td>, <td class="rate_up">103,545</td>, <td class="rate_up">262</td>, <td class="rate_down">885,293</td>, <td class="rate_down">568</td>, <td class="rate_up">275,011</td>, <td class="rate_up">19</td>, <td class="rate_up">1,059,618</td>, <td class="rate_up">2,502</td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="division_line" colspan="11"></td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="date">19.02.20</td>, <td class="rate_up">250,845</td>, <td class="rate_up">8,001</td>, <td class="rate_down">103,283</td>, <td class="rate_down">64</td>, <td class="rate_up">885,861</td>, <td class="rate_up">2,860</td>, <td class="rate_down">274,992</td>, <td class="rate_down">267</td>, <td class="rate_up">1,057,116</td>, <td class="rate_up">289</td>]
[<td class="date">19.02.19</td>, <td class="rate_down">242,844</td>, <td class="rate_down">2,770</td>, <td class="rate_up">103,347</td>, <td class="rate_up">750</td>, <td class="rate_down">883,001</td>, <td class="rate_down">1,772</td>, <td class="rate_down">275,259</td>, <td class="rate_down">326</td>, <td class="rate_up">1,056,827</td>, <td class="rate_up">360</td>]
[<td class="date">19.02.18</td>, <td class="rate_up">245,614</td>, <td class="rate_up">2,038</td>, <td class="rate_up">102,596</td>, <td class="rate_up">502</td>, <td class="rate_up">884,773</td>, <td class="rate_up">2,388</td>, <td class="rate_up">275,585</td>, <td class="rate_up">162</td>, <td class="rate_up">1,056,467</td>, <td class="rate_up">191</td>]
[<td class="date">19.02.15</td>, <td class="rate_down">243,576</td>, <td class="rate_down">1,583</td>, <td class="rate_up">102,094</td>, <td class="rate_up">292</td>, <td class="rate_down">882,385</td>, <td class="rate_down">1,478</td>, <td class="rate_up">275,423</td>, <td class="rate_up">64</td>, <td class="rate_up">1,056,276</td>, <td class="rate_up">3,710</td>]
[<td class="date">19.02.14</td>, <td class="rate_down">245,159</td>, <td class="rate_down">3,828</td>, <td class="rate_up">101,802</td>, <td class="rate_up">432</td>, <td class="rate_up">883,863</td>, <td class="rate_up">1,823</td>, <td class="rate_up">275,359</td>, <td class="rate_up">267</td>, <td class="rate_up">1,052,566</td>, <td class="rate_up">3,144</td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="division_line" colspan="11"></td>]
[<td class="blank_08" colspan="11"></td>]
[<td class="date">19.02.13</td>, <td class="rate_down">248,987</td>, <td class="rate_down">487</td>, <td class="rate_up">101,371</td>, <td class="rate_up">847</td>, <td class="rate_up">882,040</td>, <td class="rate_up">2,589</td>, <td class="rate_down">275,092</td>, <td class="rate_down">80</td>, <td class="rate_up">1,049,422</td>, <td class="rate_up">646</td>]
[<td class="date">19.02.12</td>, <td class="rate_down">249,473</td>, <td class="rate_down">12,395</td>, <td class="rate_up">100,523</td>, <td class="rate_up">1,028</td>, <td class="rate_down">879,451</td>, <td class="rate_down">450</td>, <td class="rate_down">275,172</td>, <td class="rate_down">18</td>, <td class="rate_up">1,048,776</td>, <td class="rate_up">1,643</td>]
[<td class="date">19.02.11</td>, <td class="rate_up">261,868</td>, <td class="rate_up">11,570</td>, <td class="rate_up">99,495</td>, <td class="rate_up">212</td>, <td class="rate_down">879,901</td>, <td class="rate_down">687</td>, <td class="rate_down">275,190</td>, <td class="rate_down">215</td>, <td class="rate_up">1,047,133</td>, <td class="rate_up">349</td>]
[<td class="date">19.02.08</td>, <td class="rate_down">250,298</td>, <td class="rate_down">16,328</td>, <td class="rate_down">99,283</td>, <td class="rate_down">135</td>, <td class="rate_down">880,588</td>, <td class="rate_down">4,247</td>, <td class="rate_down">275,405</td>, <td class="rate_down">53</td>, <td class="rate_up">1,046,784</td>, <td class="rate_up">1,657</td>]
[<td class="date">19.02.07</td>, <td class="rate_up">266,626</td>, <td class="rate_up">14,810</td>, <td class="rate_up">99,418</td>, <td class="rate_up">543</td>, <td class="rate_down">884,835</td>, <td class="rate_down">1,084</td>, <td class="rate_up">275,458</td>, <td class="rate_up">91</td>, <td class="rate_up">1,045,127</td>, <td class="rate_up">3,416</td>]
[<td class="blank_09" colspan="11"></td>]
[<td class="division_line_1" colspan="11"></td>]
[<td class="on">
<a href="/sise/sise_deposit.nhn?&amp;page=1">1</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=2">2</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=3">3</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=4">4</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=5">5</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=6">6</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=7">7</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=8">8</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=9">9</a>
</td>, <td>
<a href="/sise/sise_deposit.nhn?&amp;page=10">10</a>
</td>, <td class="pgR">
<a href="/sise/sise_deposit.nhn?&amp;page=11">
				다음<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
</a>
</td>, <td class="pgRR">
<a href="/sise/sise_deposit.nhn?&amp;page=208">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
</td>]

In [73]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형 펀드': [],
                  '혼합형 펀드': [],
                  '채권형 펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            count = 0 
            
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 3:
                        print(td)
get_money_trend()

<td class="date">19.03.07</td>
<td class="rate_down">247,796</td>
<td class="rate_down">127</td>
<td class="rate_up">102,702</td>
<td class="rate_up">638</td>
<td class="rate_down">868,665</td>
<td class="rate_down">3,663</td>
<td class="rate_down">275,411</td>
<td class="rate_up">1,073,283</td>
<td class="rate_up">1,756</td>
<td class="date">19.03.06</td>
<td class="rate_down">247,923</td>
<td class="rate_down">2,273</td>
<td class="rate_down">102,065</td>
<td class="rate_down">1,039</td>
<td class="rate_down">872,328</td>
<td class="rate_down">2,354</td>
<td class="rate_up">275,484</td>
<td class="rate_up">252</td>
<td class="rate_up">1,071,527</td>
<td class="date">19.03.05</td>
<td class="rate_down">250,195</td>
<td class="rate_down">11,328</td>
<td class="rate_down">103,104</td>
<td class="rate_down">1,547</td>
<td class="rate_down">874,682</td>
<td class="rate_down">892</td>
<td class="rate_up">275,232</td>
<td class="rate_up">133</td>
<td class="rate_up">1,071,485</td>
<td class="rate_up">2,625</td>
<td class="date">19.03.04</td>
<td class="rate_up">261,523</td>
<td class="rate_up">6,523</td>
<td class="rate_up">104,651</td>
<td class="rate_up">121</td>
<td class="rate_down">875,574</td>
<td class="rate_down">1,063</td>
<td class="rate_up">275,099</td>
<td class="rate_up">1,068,860</td>
<td class="rate_up">542</td>
<td class="date">19.02.28</td>
<td class="rate_down">255,000</td>
<td class="rate_down">1,436</td>
<td class="rate_up">104,531</td>
<td class="rate_up">231</td>
<td class="rate_down">876,637</td>
<td class="rate_down">5,948</td>
<td class="rate_down">275,068</td>
<td class="rate_up">1,068,318</td>
<td class="rate_up">7,119</td>
<td class="date">19.02.27</td>
<td class="rate_down">256,436</td>
<td class="rate_up">104,300</td>
<td class="rate_up">133</td>
<td class="rate_up">882,585</td>
<td class="rate_up">568</td>
<td class="rate_up">275,122</td>
<td class="rate_up">624</td>
<td class="rate_down">1,061,199</td>
<td class="rate_down">1,356</td>
<td class="date">19.02.26</td>
<td class="rate_up">256,448</td>
<td class="rate_up">7,195</td>
<td class="rate_up">104,167</td>
<td class="rate_up">133</td>
<td class="rate_down">882,017</td>
<td class="rate_down">1,929</td>
<td class="rate_up">274,498</td>
<td class="rate_up">1,062,555</td>
<td class="rate_up">2,645</td>
<td class="date">19.02.25</td>
<td class="rate_up">249,253</td>
<td class="rate_up">3,581</td>
<td class="rate_up">104,034</td>
<td class="rate_up">333</td>
<td class="rate_down">883,946</td>
<td class="rate_down">918</td>
<td class="rate_down">274,463</td>
<td class="rate_down">338</td>
<td class="rate_up">1,059,910</td>
<td class="rate_up">1,142</td>
<td class="date">19.02.22</td>
<td class="rate_up">245,671</td>
<td class="rate_up">419</td>
<td class="rate_up">103,701</td>
<td class="rate_up">156</td>
<td class="rate_down">884,864</td>
<td class="rate_down">429</td>
<td class="rate_down">274,801</td>
<td class="rate_down">210</td>
<td class="rate_down">1,058,768</td>
<td class="rate_down">850</td>
<td class="date">19.02.21</td>
<td class="rate_down">245,252</td>
<td class="rate_down">5,593</td>
<td class="rate_up">103,545</td>
<td class="rate_up">262</td>
<td class="rate_down">885,293</td>
<td class="rate_down">568</td>
<td class="rate_up">275,011</td>
<td class="rate_up">1,059,618</td>
<td class="rate_up">2,502</td>
<td class="date">19.02.20</td>
<td class="rate_up">250,845</td>
<td class="rate_up">8,001</td>
<td class="rate_down">103,283</td>
<td class="rate_up">885,861</td>
<td class="rate_up">2,860</td>
<td class="rate_down">274,992</td>
<td class="rate_down">267</td>
<td class="rate_up">1,057,116</td>
<td class="rate_up">289</td>
<td class="date">19.02.19</td>
<td class="rate_down">242,844</td>
<td class="rate_down">2,770</td>
<td class="rate_up">103,347</td>
<td class="rate_up">750</td>
<td class="rate_down">883,001</td>
<td class="rate_down">1,772</td>
<td class="rate_down">275,259</td>
<td class="rate_down">326</td>
<td class="rate_up">1,056,827</td>
<td class="rate_up">360</td>
<td class="date">19.02.18</td>
<td class="rate_up">245,614</td>
<td class="rate_up">2,038</td>
<td class="rate_up">102,596</td>
<td class="rate_up">502</td>
<td class="rate_up">884,773</td>
<td class="rate_up">2,388</td>
<td class="rate_up">275,585</td>
<td class="rate_up">162</td>
<td class="rate_up">1,056,467</td>
<td class="rate_up">191</td>
<td class="date">19.02.15</td>
<td class="rate_down">243,576</td>
<td class="rate_down">1,583</td>
<td class="rate_up">102,094</td>
<td class="rate_up">292</td>
<td class="rate_down">882,385</td>
<td class="rate_down">1,478</td>
<td class="rate_up">275,423</td>
<td class="rate_up">1,056,276</td>
<td class="rate_up">3,710</td>
<td class="date">19.02.14</td>
<td class="rate_down">245,159</td>
<td class="rate_down">3,828</td>
<td class="rate_up">101,802</td>
<td class="rate_up">432</td>
<td class="rate_up">883,863</td>
<td class="rate_up">1,823</td>
<td class="rate_up">275,359</td>
<td class="rate_up">267</td>
<td class="rate_up">1,052,566</td>
<td class="rate_up">3,144</td>
<td class="date">19.02.13</td>
<td class="rate_down">248,987</td>
<td class="rate_down">487</td>
<td class="rate_up">101,371</td>
<td class="rate_up">847</td>
<td class="rate_up">882,040</td>
<td class="rate_up">2,589</td>
<td class="rate_down">275,092</td>
<td class="rate_up">1,049,422</td>
<td class="rate_up">646</td>
<td class="date">19.02.12</td>
<td class="rate_down">249,473</td>
<td class="rate_down">12,395</td>
<td class="rate_up">100,523</td>
<td class="rate_up">1,028</td>
<td class="rate_down">879,451</td>
<td class="rate_down">450</td>
<td class="rate_down">275,172</td>
<td class="rate_up">1,048,776</td>
<td class="rate_up">1,643</td>
<td class="date">19.02.11</td>
<td class="rate_up">261,868</td>
<td class="rate_up">11,570</td>
<td class="rate_up">99,495</td>
<td class="rate_up">212</td>
<td class="rate_down">879,901</td>
<td class="rate_down">687</td>
<td class="rate_down">275,190</td>
<td class="rate_down">215</td>
<td class="rate_up">1,047,133</td>
<td class="rate_up">349</td>
<td class="date">19.02.08</td>
<td class="rate_down">250,298</td>
<td class="rate_down">16,328</td>
<td class="rate_down">99,283</td>
<td class="rate_down">135</td>
<td class="rate_down">880,588</td>
<td class="rate_down">4,247</td>
<td class="rate_down">275,405</td>
<td class="rate_up">1,046,784</td>
<td class="rate_up">1,657</td>
<td class="date">19.02.07</td>
<td class="rate_up">266,626</td>
<td class="rate_up">14,810</td>
<td class="rate_up">99,418</td>
<td class="rate_up">543</td>
<td class="rate_down">884,835</td>
<td class="rate_down">1,084</td>
<td class="rate_up">275,458</td>
<td class="rate_up">1,045,127</td>
<td class="rate_up">3,416</td>

In [76]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형펀드','혼합형펀드','채권형펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형펀드': [],
                  '혼합형펀드': [],
                  '채권형펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            count = 0 
            
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            #print("loop : {}".format(i))
                            date_list.append(date_)
                            print(date_list)
                        elif count == 1:
                            고객예탁금 = td.text.strip()
                            dictionary['고객예탁금'].append(고객예탁금)
                            print(dictionary['고객예탁금'])
                        elif count == 3:
                            신용잔고 = td.text.strip()
                            dictionary['신용잔고'].append(신용잔고)
                            print(dictionary['신용잔고'])
                        elif count == 5:
                            주식형펀드 = td.text.strip()
                            dictionary['주식형펀드'].append(주식형펀드)
                            print(dictionary['주식형펀드'])
                        elif count == 7:
                            혼합형펀드 = td.text.strip()
                            dictionary['혼합형펀드'].append(혼합형펀드)
                            print(dictionary['혼합형펀드'])
                        elif count == 9:
                            채권형펀드 = td.text.strip()
                            dictionary['채권형펀드'].append(채권형펀드)
                            print(dictionary['채권형펀드'])
                    count += 1
                    print('count:{}'.format(count))

get_money_trend()

count:1
['19-03-07']
count:1
['247,796']
count:2
count:3
['102,702']
count:4
count:5
['868,665']
count:6
count:7
['275,411']
count:8
count:9
['1,073,283']
count:10
count:11
['19-03-07', '19-03-06']
count:1
['247,796', '247,923']
count:2
count:3
['102,702', '102,065']
count:4
count:5
['868,665', '872,328']
count:6
count:7
['275,411', '275,484']
count:8
count:9
['1,073,283', '1,071,527']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05']
count:1
['247,796', '247,923', '250,195']
count:2
count:3
['102,702', '102,065', '103,104']
count:4
count:5
['868,665', '872,328', '874,682']
count:6
count:7
['275,411', '275,484', '275,232']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04']
count:1
['247,796', '247,923', '250,195', '261,523']
count:2
count:3
['102,702', '102,065', '103,104', '104,651']
count:4
count:5
['868,665', '872,328', '874,682', '875,574']
count:6
count:7
['275,411', '275,484', '275,232', '275,099']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318']
count:10
count:11
count:1
count:1
count:1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618']
count:10
count:11
count:1
count:1
count:1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566']
count:10
count:11
count:1
count:1
count:1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868', '250,298']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495', '99,283']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901', '880,588']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190', '275,405']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133', '1,046,784']
count:10
count:11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07']
count:1
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868', '250,298', '266,626']
count:2
count:3
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495', '99,283', '99,418']
count:4
count:5
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901', '880,588', '884,835']
count:6
count:7
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190', '275,405', '275,458']
count:8
count:9
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133', '1,046,784', '1,045,127']
count:10
count:11
count:1
count:1
count:1
count:2
count:3
count:4
count:5
count:6
count:7
count:8
count:9
count:10
count:11
count:12

In [61]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형 펀드': [],
                  '혼합형 펀드': [],
                  '채권형 펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,2):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            count = 0 
            
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            #print("loop : {}".format(i))
                            date_list.append(date_)
                            print(date_list)
                        elif count in mask:
                            print("count={}".format(count))
                            temp = int((count-1)/2)
                            print("temp={}".format(temp))
                            dictionary[name_list[temp]].append(td.text.strip())
                            print(dictionary[name_list[temp]])
        
                    count += 1
                    print(count)

get_money_trend()

1
['19-03-07']
1
count=1
temp=0
['247,796']
2
3
count=3
temp=1
['102,702']
4
5
count=5
temp=2
['868,665']
6
7
count=7
temp=3
['275,411']
8
9
count=9
temp=4
['1,073,283']
10
11
['19-03-07', '19-03-06']
1
count=1
temp=0
['247,796', '247,923']
2
3
count=3
temp=1
['102,702', '102,065']
4
5
count=5
temp=2
['868,665', '872,328']
6
7
count=7
temp=3
['275,411', '275,484']
8
9
count=9
temp=4
['1,073,283', '1,071,527']
10
11
['19-03-07', '19-03-06', '19-03-05']
1
count=1
temp=0
['247,796', '247,923', '250,195']
2
3
count=3
temp=1
['102,702', '102,065', '103,104']
4
5
count=5
temp=2
['868,665', '872,328', '874,682']
6
7
count=7
temp=3
['275,411', '275,484', '275,232']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318']
10
11
1
1
1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618']
10
11
1
1
1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566']
10
11
1
1
1
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868', '250,298']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495', '99,283']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901', '880,588']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190', '275,405']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133', '1,046,784']
10
11
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07']
1
count=1
temp=0
['247,796', '247,923', '250,195', '261,523', '255,000', '256,436', '256,448', '249,253', '245,671', '245,252', '250,845', '242,844', '245,614', '243,576', '245,159', '248,987', '249,473', '261,868', '250,298', '266,626']
2
3
count=3
temp=1
['102,702', '102,065', '103,104', '104,651', '104,531', '104,300', '104,167', '104,034', '103,701', '103,545', '103,283', '103,347', '102,596', '102,094', '101,802', '101,371', '100,523', '99,495', '99,283', '99,418']
4
5
count=5
temp=2
['868,665', '872,328', '874,682', '875,574', '876,637', '882,585', '882,017', '883,946', '884,864', '885,293', '885,861', '883,001', '884,773', '882,385', '883,863', '882,040', '879,451', '879,901', '880,588', '884,835']
6
7
count=7
temp=3
['275,411', '275,484', '275,232', '275,099', '275,068', '275,122', '274,498', '274,463', '274,801', '275,011', '274,992', '275,259', '275,585', '275,423', '275,359', '275,092', '275,172', '275,190', '275,405', '275,458']
8
9
count=9
temp=4
['1,073,283', '1,071,527', '1,071,485', '1,068,860', '1,068,318', '1,061,199', '1,062,555', '1,059,910', '1,058,768', '1,059,618', '1,057,116', '1,056,827', '1,056,467', '1,056,276', '1,052,566', '1,049,422', '1,048,776', '1,047,133', '1,046,784', '1,045,127']
10
11
1
1
1
2
3
4
5
6
7
8
9
10
11
12

In [95]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
from urllib.request import urlopen

url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='        

source = urlopen(url).read()   # 지정한 페이지에서 코드 읽기
source = BeautifulSoup(source, 'lxml')   # 뷰티풀 스프로 태그별로 코드 분류

last = source.find('td',class_='pgRR').find('a')['href']
last = last.split('&')[1]
last = last.split('=')[1]
last = int(last)

# 사용자의 PC내 폴더 주소를 입력하시면 됩니다.
path = 'd:\\money_trend.xlsx'

def get_money_trend():

    Data = DataFrame(columns = ['고객예탁금', '신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드'])

    # 날짜를 받을 리스트
    date_list = []

    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],
                  '신용잔고': [],
                  '주식형 펀드': [],
                  '혼합형 펀드': [],
                  '채권형 펀드': []
                  }

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형 펀드','혼합형 펀드','채권형 펀드']


    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,3):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            count = 0 
            
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            #print("loop : {}".format(i))
                            date_list.append(date_)
                            print(date_list)
                        elif count in mask:
                            #print("count={}".format(count))
                            temp = int((count-1)/2)
                            #print("temp={}".format(temp))
                            dictionary[name_list[temp]].append(td.text.strip())
                            #print(dictionary[name_list[temp]])
        
                    count += 1

get_money_trend()

['19-03-07']
['19-03-07', '19-03-06']
['19-03-07', '19-03-06', '19-03-05']
['19-03-07', '19-03-06', '19-03-05', '19-03-04']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14', '19-01-11']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14', '19-01-11', '19-01-10']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14', '19-01-11', '19-01-10', '19-01-09']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14', '19-01-11', '19-01-10', '19-01-09', '19-01-08']
['19-03-07', '19-03-06', '19-03-05', '19-03-04', '19-02-28', '19-02-27', '19-02-26', '19-02-25', '19-02-22', '19-02-21', '19-02-20', '19-02-19', '19-02-18', '19-02-15', '19-02-14', '19-02-13', '19-02-12', '19-02-11', '19-02-08', '19-02-07', '19-02-01', '19-01-31', '19-01-30', '19-01-29', '19-01-28', '19-01-25', '19-01-24', '19-01-23', '19-01-22', '19-01-21', '19-01-18', '19-01-17', '19-01-16', '19-01-15', '19-01-14', '19-01-11', '19-01-10', '19-01-09', '19-01-08', '19-01-07']

# first

In [137]:
def get_moneytrend():
    
    path = 'd:\\kkang.xlsx'
    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page=' 
    source = urlopen(naver_url).read()
    source = BeautifulSoup(source, 'lxml')
 
    last_page = 0
    last_page = source.find('td', class_='pgRR').find('a')['href']
    last_page = last_page.split('&')[1]
    last_page = last_page.split('=')[1]
    last_page = int(last_page)
    
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,last_page+1):
        print(i)
get_moneytrend()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543

In [153]:
def get_moneytrend():
    
    path = 'd:\\kkang.xlsx'
    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='    
    source = urlopen(naver_url).read()
    source = BeautifulSoup(source, 'lxml')
 
    last_page = 0
    last_page = source.find('td', class_='pgRR').find('a')['href']
    last_page = last_page.split('&')[1]
    last_page = last_page.split('=')[1]
    last_page = int(last_page)
    
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,last_page):
        source = urlopen(naver_url).read()
        source = BeautifulSoup(source, 'lxml')
        
        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            count = 0
    
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            date_list.append(date_)
                            print(date_list)                               
                        elif count in mask:
                            temp = int((count-1)/2)
                            dictionary[name_list[temp]].append(td.text.strip())
                                    
                    count += 1
        print(str(i) + '번째 페이지 크롤링 완료')
        if i == last_page-1:
            df = pd.DataFrame(dictionary,index = date_list)
            df = df.sort_index()
            df.고객예탁금 = df.고객예탁금.str.replace(',','')
            df.신용잔고 = df.신용잔고.str.replace(',','')
            df.주식형펀드 = df.주식형펀드.str.replace(',','')
            df.혼합형펀드 = df.혼합형펀드.str.replace(',','')
            df.채권형펀드 = df.채권형펀드.str.replace(',','')
            #df.to_excel(path, encoding='utf-8')
            print(df)
get_moneytrend()

AttributeError: 'NoneType' object has no attribute 'find'

In [156]:
def get_moneytrend():
    
    
    path = 'd:\\kkang.xlsx'
    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='
    
    source = urlopen(url).read()
    source = BeautifulSoup(source, 'lxml')
 
    last_page = 0
    last_page = source.find('td', class_='pgRR').find('a')['href']
    last_page = last_page.split('&')[1]
    last_page = last_page.split('=')[1]
    last_page = int(last_page)
    print(last_page)
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,last_page):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            count = 0
    
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            date_list.append(date_)
                            #print(date_list)                               
                        elif count in mask:
                            temp = int((count-1)/2)
                            dictionary[name_list[temp]].append(td.text.strip())
                                    
                    count += 1
        print(str(i) + '번째 페이지 크롤링 완료')
        if i == last_page-1:
            date_list.pop(-1)
            df = pd.DataFrame(dictionary,index = date_list)
            df = df.sort_index()
            df.고객예탁금 = df.고객예탁금.str.replace(',','')
            df.신용잔고 = df.신용잔고.str.replace(',','')
            df.주식형펀드 = df.주식형펀드.str.replace(',','')
            df.혼합형펀드 = df.혼합형펀드.str.replace(',','')
            df.채권형펀드 = df.채권형펀드.str.replace(',','')
            #df.to_excel(path, encoding='utf-8')
            print(df)
get_moneytrend()

208
1번째 페이지 크롤링 완료
2번째 페이지 크롤링 완료
3번째 페이지 크롤링 완료
4번째 페이지 크롤링 완료
5번째 페이지 크롤링 완료
6번째 페이지 크롤링 완료
7번째 페이지 크롤링 완료
8번째 페이지 크롤링 완료
9번째 페이지 크롤링 완료
10번째 페이지 크롤링 완료
11번째 페이지 크롤링 완료
12번째 페이지 크롤링 완료
13번째 페이지 크롤링 완료
14번째 페이지 크롤링 완료
15번째 페이지 크롤링 완료
16번째 페이지 크롤링 완료
17번째 페이지 크롤링 완료
18번째 페이지 크롤링 완료
19번째 페이지 크롤링 완료
20번째 페이지 크롤링 완료
21번째 페이지 크롤링 완료
22번째 페이지 크롤링 완료
23번째 페이지 크롤링 완료
24번째 페이지 크롤링 완료
25번째 페이지 크롤링 완료
26번째 페이지 크롤링 완료
27번째 페이지 크롤링 완료
28번째 페이지 크롤링 완료
29번째 페이지 크롤링 완료
30번째 페이지 크롤링 완료
31번째 페이지 크롤링 완료
32번째 페이지 크롤링 완료
33번째 페이지 크롤링 완료
34번째 페이지 크롤링 완료
35번째 페이지 크롤링 완료
36번째 페이지 크롤링 완료
37번째 페이지 크롤링 완료
38번째 페이지 크롤링 완료
39번째 페이지 크롤링 완료
40번째 페이지 크롤링 완료
41번째 페이지 크롤링 완료
42번째 페이지 크롤링 완료
43번째 페이지 크롤링 완료
44번째 페이지 크롤링 완료
45번째 페이지 크롤링 완료
46번째 페이지 크롤링 완료
47번째 페이지 크롤링 완료
48번째 페이지 크롤링 완료
49번째 페이지 크롤링 완료
50번째 페이지 크롤링 완료
51번째 페이지 크롤링 완료
52번째 페이지 크롤링 완료
53번째 페이지 크롤링 완료
54번째 페이지 크롤링 완료
55번째 페이지 크롤링 완료
56번째 페이지 크롤링 완료
57번째 페이지 크롤링 완료
58번째 페이지 크롤링 완료
59번째 페이지 크롤링 완료
60번째 페이지 크롤링 완료
61번째 페이지 크롤링 완료
62번째 페이지 크롤링 완료
63번째 페이지 크롤링 완료
64번째 페이지 크롤링 완료
65번째 페이지 크롤링 완료
66번째 페이지 크롤링 완료
67번째 페이지 크롤링 완료
68번째 페이지 크롤링 완료
69번째 페이지 크롤링 완료
70번째 페이지 크롤링 완료
71번째 페이지 크롤링 완료
72번째 페이지 크롤링 완료
73번째 페이지 크롤링 완료
74번째 페이지 크롤링 완료
75번째 페이지 크롤링 완료
76번째 페이지 크롤링 완료
77번째 페이지 크롤링 완료
78번째 페이지 크롤링 완료
79번째 페이지 크롤링 완료
80번째 페이지 크롤링 완료
81번째 페이지 크롤링 완료
82번째 페이지 크롤링 완료
83번째 페이지 크롤링 완료
84번째 페이지 크롤링 완료
85번째 페이지 크롤링 완료
86번째 페이지 크롤링 완료
87번째 페이지 크롤링 완료
88번째 페이지 크롤링 완료
89번째 페이지 크롤링 완료
90번째 페이지 크롤링 완료
91번째 페이지 크롤링 완료
92번째 페이지 크롤링 완료
93번째 페이지 크롤링 완료
94번째 페이지 크롤링 완료
95번째 페이지 크롤링 완료
96번째 페이지 크롤링 완료
97번째 페이지 크롤링 완료
98번째 페이지 크롤링 완료
99번째 페이지 크롤링 완료
100번째 페이지 크롤링 완료
101번째 페이지 크롤링 완료
102번째 페이지 크롤링 완료
103번째 페이지 크롤링 완료
104번째 페이지 크롤링 완료
105번째 페이지 크롤링 완료
106번째 페이지 크롤링 완료
107번째 페이지 크롤링 완료
108번째 페이지 크롤링 완료
109번째 페이지 크롤링 완료
110번째 페이지 크롤링 완료
111번째 페이지 크롤링 완료
112번째 페이지 크롤링 완료
113번째 페이지 크롤링 완료
114번째 페이지 크롤링 완료
115번째 페이지 크롤링 완료
116번째 페이지 크롤링 완료
117번째 페이지 크롤링 완료
118번째 페이지 크롤링 완료
119번째 페이지 크롤링 완료
120번째 페이지 크롤링 완료
121번째 페이지 크롤링 완료
122번째 페이지 크롤링 완료
123번째 페이지 크롤링 완료
124번째 페이지 크롤링 완료
125번째 페이지 크롤링 완료
126번째 페이지 크롤링 완료
127번째 페이지 크롤링 완료
128번째 페이지 크롤링 완료
129번째 페이지 크롤링 완료
130번째 페이지 크롤링 완료
131번째 페이지 크롤링 완료
132번째 페이지 크롤링 완료
133번째 페이지 크롤링 완료
134번째 페이지 크롤링 완료
135번째 페이지 크롤링 완료
136번째 페이지 크롤링 완료
137번째 페이지 크롤링 완료
138번째 페이지 크롤링 완료
139번째 페이지 크롤링 완료
140번째 페이지 크롤링 완료
141번째 페이지 크롤링 완료
142번째 페이지 크롤링 완료
143번째 페이지 크롤링 완료
144번째 페이지 크롤링 완료
145번째 페이지 크롤링 완료
146번째 페이지 크롤링 완료
147번째 페이지 크롤링 완료
148번째 페이지 크롤링 완료
149번째 페이지 크롤링 완료
150번째 페이지 크롤링 완료
151번째 페이지 크롤링 완료
152번째 페이지 크롤링 완료
153번째 페이지 크롤링 완료
154번째 페이지 크롤링 완료
155번째 페이지 크롤링 완료
156번째 페이지 크롤링 완료
157번째 페이지 크롤링 완료
158번째 페이지 크롤링 완료
159번째 페이지 크롤링 완료
160번째 페이지 크롤링 완료
161번째 페이지 크롤링 완료
162번째 페이지 크롤링 완료
163번째 페이지 크롤링 완료
164번째 페이지 크롤링 완료
165번째 페이지 크롤링 완료
166번째 페이지 크롤링 완료
167번째 페이지 크롤링 완료
168번째 페이지 크롤링 완료
169번째 페이지 크롤링 완료
170번째 페이지 크롤링 완료
171번째 페이지 크롤링 완료
172번째 페이지 크롤링 완료
173번째 페이지 크롤링 완료
174번째 페이지 크롤링 완료
175번째 페이지 크롤링 완료
176번째 페이지 크롤링 완료
177번째 페이지 크롤링 완료
178번째 페이지 크롤링 완료
179번째 페이지 크롤링 완료
180번째 페이지 크롤링 완료
181번째 페이지 크롤링 완료
182번째 페이지 크롤링 완료
183번째 페이지 크롤링 완료
184번째 페이지 크롤링 완료
185번째 페이지 크롤링 완료
186번째 페이지 크롤링 완료
187번째 페이지 크롤링 완료
188번째 페이지 크롤링 완료
189번째 페이지 크롤링 완료
190번째 페이지 크롤링 완료
191번째 페이지 크롤링 완료
192번째 페이지 크롤링 완료
193번째 페이지 크롤링 완료
194번째 페이지 크롤링 완료
195번째 페이지 크롤링 완료
196번째 페이지 크롤링 완료
197번째 페이지 크롤링 완료
198번째 페이지 크롤링 완료
199번째 페이지 크롤링 완료
200번째 페이지 크롤링 완료
201번째 페이지 크롤링 완료
202번째 페이지 크롤링 완료
203번째 페이지 크롤링 완료
204번째 페이지 크롤링 완료
205번째 페이지 크롤링 완료
206번째 페이지 크롤링 완료
207번째 페이지 크롤링 완료

ValueError: Shape of passed values is (4140, 5), indices imply (4139, 5)

In [147]:
def get_moneytrend():
    
    
    path = 'd:\\kkang.xlsx'
    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='    
    
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,5):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')
        last = source.find('td',class_='pgRR').find('a')['href']
        last = last.split('&')[1]
        last = last.split('=')[1]
        last = int(last)

        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            count = 0
    
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            date_list.append(date_)
                            #print(date_list)                               
                        elif count in mask:
                            temp = int((count-1)/2)
                            dictionary[name_list[temp]].append(td.text.strip())
                                    
                    count += 1
        print(str(i) + '번째 페이지 크롤링 완료')
        if i == 4:
            df = pd.DataFrame(dictionary,index = date_list)
            df = df.sort_index()
            df.고객예탁금 = df.고객예탁금.str.replace(',','')
            df.신용잔고 = df.신용잔고.str.replace(',','')
            df.주식형펀드 = df.주식형펀드.str.replace(',','')
            df.혼합형펀드 = df.혼합형펀드.str.replace(',','')
            df.채권형펀드 = df.채권형펀드.str.replace(',','')
            #df.to_excel(path, encoding='utf-8')
            print(df)
get_moneytrend()

1번째 페이지 크롤링 완료
2번째 페이지 크롤링 완료
3번째 페이지 크롤링 완료
4번째 페이지 크롤링 완료
           고객예탁금    신용잔고   주식형펀드   혼합형펀드    채권형펀드
18-11-07  240595   91328  816411  281638  1008258
18-11-08  242981   92366  818218  281480  1006824
18-11-09  234717   93227  817010  281671  1006715
18-11-12  238050   93475  814711  281162  1005895
18-11-13  235153   94061  814076  281253  1005793
18-11-14  243355   93814  813176  281239  1001196
18-11-15  246701   93582  816795  281368  1003322
18-11-16  230507   93836  816983  281478  1005920
18-11-19  230858   93906  820602  281435  1006802
18-11-20  261964   94110  819029  281659  1008027
18-11-21  264618   94539  821272  281586  1008455
18-11-22  260455   95495  821949  281601  1007645
18-11-23  235340   96144  821424  281264  1010226
18-11-26  235416   96606  826576  281138  1009024
18-11-27  228658   96245  831864  281269  1012190
18-11-28  230984   95468  834981  281295  1012213
18-11-29  229296   95418  836093  281221  1010770
18-11-30  226677   95765  836413  281574  1012349
18-12-03  237931   95583  839263  281543  1013739
18-12-04  230320   95833  835006  281510  1012657
18-12-05  234649   95802  833490  281447  1011757
18-12-06  237665   96573  828380  281366  1013931
18-12-07  226028   97037  828475  281540  1015573
18-12-10  238520   96824  824727  281482  1017196
18-12-11  232724   96449  821370  281689  1017889
18-12-12  229994   96159  826678  281649  1016013
18-12-13  231431   95671  827996  281502  1015957
18-12-14  225662   95272  826538  281521  1015573
18-12-17  231707   95351  832237  281440  1014917
18-12-18  229964   95676  831419  281436  1017023
...          ...     ...     ...     ...      ...
19-01-21  257131   96208  870010  278345  1029642
19-01-22  238833   96405  869312  278338  1029094
19-01-23  236726   97262  869540  277856  1029809
19-01-24  237513   97664  871937  277800  1030840
19-01-25  235131   97811  877572  277687  1032624
19-01-28  242686   98142  877199  278957  1033544
19-01-29  301450   97428  881951  279009  1036403
19-01-30  288905   98229  884672  278224  1039579
19-01-31  282083   98843  884180  275677  1040890
19-02-01  251816   98875  885919  275367  1041711
19-02-07  266626   99418  884835  275458  1045127
19-02-08  250298   99283  880588  275405  1046784
19-02-11  261868   99495  879901  275190  1047133
19-02-12  249473  100523  879451  275172  1048776
19-02-13  248987  101371  882040  275092  1049422
19-02-14  245159  101802  883863  275359  1052566
19-02-15  243576  102094  882385  275423  1056276
19-02-18  245614  102596  884773  275585  1056467
19-02-19  242844  103347  883001  275259  1056827
19-02-20  250845  103283  885861  274992  1057116
19-02-21  245252  103545  885293  275011  1059618
19-02-22  245671  103701  884864  274801  1058768
19-02-25  249253  104034  883946  274463  1059910
19-02-26  256448  104167  882017  274498  1062555
19-02-27  256436  104300  882585  275122  1061199
19-02-28  255000  104531  876637  275068  1068318
19-03-04  261523  104651  875574  275099  1068860
19-03-05  250195  103104  874682  275232  1071485
19-03-06  247923  102065  872328  275484  1071527
19-03-07  247796  102702  868665  275411  1073283

[80 rows x 5 columns]

In [96]:
def get_moneytrend():
    
    path = 'd:\\kkang.xlsx'

    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page='    
    
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,3):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            count = 0
    
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                            date_list.append(date_)
                                                            
                        elif count in mask:
                            temp = int((count-1)/2)
                            dictionary[name_list[temp]].append(td.text.strip())
                                    
                    count += 1
            
            # 누락된 값을 발견하면 (펀드 자료에 누락된 값이 존재함)
            if len(dictionary['고객예탁금']) != len(dictionary['주식형펀드']):
                print(str(i)+ '번째 페이지에서 누락된 값 발생')
                print('누락된 데이터를 제거합니다')
                    
                date_list.pop(-1)
                dictionary['고객예탁금'].pop(-1)
                dictionary['신용잔고'].pop(-1)
               

        print(str(i) + '번째 페이지 크롤링 완료')
        df = pd.DataFrame(dictionary,index = date_list)
        df = df.sort_index()
        df.고객예탁금 = df.고객예탁금.str.replace(',','')
        df.신용잔고 = df.신용잔고.str.replace(',','')
        df.주식형펀드 = df.주식형펀드.str.replace(',','')
        df.혼합형펀드 = df.혼합형펀드.str.replace(',','')
        df.채권형펀드 = df.채권형펀드.str.replace(',','')
        #df.to_excel(path, encoding='utf-8')
            
        return df

get_moneytrend()

1번째 페이지 크롤링 완료

           고객예탁금    신용잔고   주식형펀드   혼합형펀드    채권형펀드
19-02-07  266626   99418  884835  275458  1045127
19-02-08  250298   99283  880588  275405  1046784
19-02-11  261868   99495  879901  275190  1047133
19-02-12  249473  100523  879451  275172  1048776
19-02-13  248987  101371  882040  275092  1049422
19-02-14  245159  101802  883863  275359  1052566
19-02-15  243576  102094  882385  275423  1056276
19-02-18  245614  102596  884773  275585  1056467
19-02-19  242844  103347  883001  275259  1056827
19-02-20  250845  103283  885861  274992  1057116
19-02-21  245252  103545  885293  275011  1059618
19-02-22  245671  103701  884864  274801  1058768
19-02-25  249253  104034  883946  274463  1059910
19-02-26  256448  104167  882017  274498  1062555
19-02-27  256436  104300  882585  275122  1061199
19-02-28  255000  104531  876637  275068  1068318
19-03-04  261523  104651  875574  275099  1068860
19-03-05  250195  103104  874682  275232  1071485
19-03-06  247923  102065  872328  275484  1071527
19-03-07  247796  102702  868665  275411  1073283

In [135]:
def get_moneytrend():
    
    path = 'd:\\kkang.xlsx'
    url = 'http://finance.naver.com/sise/sise_deposit.nhn?&page=' 
    source = urlopen(naver_url).read()
    source = BeautifulSoup(source, 'lxml')
 
    last_page = 0
    last_page = source.find('td', class_='pgRR').find('a')['href']
    last_page = last_page.split('&')[1]
    last_page = last_page.split('=')[1]
    last_page = int(last_page)
    
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'고객예탁금': [],'신용잔고': [],'주식형펀드': [],'혼합형펀드': [],'채권형펀드': []}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['고객예탁금','신용잔고','주식형펀드','혼합형펀드','채권형펀드']

    # count mask
    mask = [0,1,3,5,7,9]
    
    for i in range(1,last_page+1):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('div',{'id':'wrap'}).find('div',{'class':'box_type_m'})
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            count = 0
    
            for td in tds:
                # 변화량 제외하고 잔고량만 가져오기
                if not td.text.strip() == 0:
                    if len(td.text.strip()) >= 4:
            
                        if count == 0:
                            date_ = td.text.strip().replace('.','-')
                        
                            if not date_ in date_list:
                                date_list.append(date_)
                                                            
                        elif count in mask:
                            temp = int((count-1)/2)
                            dictionary[name_list[temp]].append(td.text.strip())
                                    
                    count += 1
            
            # 누락된 값을 발견하면 (펀드 자료에 누락된 값이 존재함)
            if len(dictionary['고객예탁금']) != len(dictionary['주식형펀드']):
                print(str(i)+ '번째 페이지에서 누락된 값 발생')
                print('누락된 데이터를 제거합니다')
                    
                date_list.pop(-1)
                dictionary['고객예탁금'].pop(-1)
                dictionary['신용잔고'].pop(-1)
               

        print(str(i) + '번째 페이지 크롤링 완료')
        df = pd.DataFrame(dictionary,index = date_list)
        df = df.sort_index()
        df.고객예탁금 = df.고객예탁금.str.replace(',','')
        df.신용잔고 = df.신용잔고.str.replace(',','')
        df.주식형펀드 = df.주식형펀드.str.replace(',','')
        df.혼합형펀드 = df.혼합형펀드.str.replace(',','')
        df.채권형펀드 = df.채권형펀드.str.replace(',','')
        df.to_excel(path, encoding='utf-8')
        
        return df

get_moneytrend()

1번째 페이지 크롤링 완료

           고객예탁금    신용잔고   주식형펀드   혼합형펀드    채권형펀드
19-02-07  266626   99418  884835  275458  1045127
19-02-08  250298   99283  880588  275405  1046784
19-02-11  261868   99495  879901  275190  1047133
19-02-12  249473  100523  879451  275172  1048776
19-02-13  248987  101371  882040  275092  1049422
19-02-14  245159  101802  883863  275359  1052566
19-02-15  243576  102094  882385  275423  1056276
19-02-18  245614  102596  884773  275585  1056467
19-02-19  242844  103347  883001  275259  1056827
19-02-20  250845  103283  885861  274992  1057116
19-02-21  245252  103545  885293  275011  1059618
19-02-22  245671  103701  884864  274801  1058768
19-02-25  249253  104034  883946  274463  1059910
19-02-26  256448  104167  882017  274498  1062555
19-02-27  256436  104300  882585  275122  1061199
19-02-28  255000  104531  876637  275068  1068318
19-03-04  261523  104651  875574  275099  1068860
19-03-05  250195  103104  874682  275232  1071485
19-03-06  247923  102065  872328  275484  1071527
19-03-07  247796  102702  868665  275411  1073283

In [52]:
    def get_kpi200():
    
        path = 'd:\\kpi200.xlsx'
        
        url = 'https://finance.naver.com/sise/sise_index_day.nhn?code=KPI200&page='
        Data = pd.DataFrame(columns = ['KPI200','거래량'])
        date_list = []
    
        # 값을 받을 사전
        dictionary = {'KPI200': [],'거래량': []}

        # dictionary key 인덱싱을 위한 리스트
        name_list = ['KPI200','거래량']

        # count mask
        mask = [0,1,5]
    
        for i in range(1,700):
            source = urlopen(url+ str(i)).read()
            source = BeautifulSoup(source,'lxml')

            tbody = source.find('div',{'class':'box_type_m'})
            trs = tbody.find_all('tr')
            for tr in trs:
                tds = tr.find_all('td')
                count = 0
    
                for td in tds:
                    # 변화량 제외하고 잔고량만 가져오기
                    if not td.text.strip() == 0:
                        if len(td.text.strip()) >= 4:
            
                            if count == 0:
                                date_ = td.text.strip().replace('.','-')
                        
                                if not date_ in date_list :
                                    date_list.append(date_)
                                    
                                #마지막 페이지인 경우
                                else:
                                    print(str(i-1) + '번째 페이지에서 크롤링 종료')
                                    df = pd.DataFrame(dictionary,index = date_list)
                                    df = df.sort_index()
                                    df.거래량 = df.거래량.str.replace(',','')
                                    df.to_excel(path, encoding='utf-8')
                                
                                    return df

                            elif count in mask:
                                print("count={}".format(count))
                                temp = int(count/5)
                                print("temp={}".format(temp))
                                dictionary[name_list[temp]].append(td.text.strip())
                                
                        #print(count)
                        count += 1
            
                # 누락된 값을 발견하면 (펀드 자료에 누락된 값이 존재함)
                if len(dictionary['KPI200']) != len(dictionary['거래량']):
                    print(str(i)+ '번째 페이지에서 누락된 값 발생')
                    print('누락된 데이터를 제거합니다')
                    
                    date_list.pop(-1)
                    dictionary['KPI200'].pop(-1)
                    dictionary['거래량'].pop(-1)
                
            print(str(i) + '번째 페이지 크롤링 완료')

In [53]:
get_kpi200()

1번째 페이지 크롤링 완료
2번째 페이지 크롤링 완료
3번째 페이지 크롤링 완료
4번째 페이지 크롤링 완료
5번째 페이지 크롤링 완료
6번째 페이지 크롤링 완료
7번째 페이지 크롤링 완료
8번째 페이지 크롤링 완료
9번째 페이지 크롤링 완료
10번째 페이지 크롤링 완료
11번째 페이지 크롤링 완료
12번째 페이지 크롤링 완료
13번째 페이지 크롤링 완료
14번째 페이지 크롤링 완료
15번째 페이지 크롤링 완료
16번째 페이지 크롤링 완료
17번째 페이지 크롤링 완료
18번째 페이지 크롤링 완료
19번째 페이지 크롤링 완료
20번째 페이지 크롤링 완료
21번째 페이지 크롤링 완료
22번째 페이지 크롤링 완료
23번째 페이지 크롤링 완료
24번째 페이지 크롤링 완료
25번째 페이지 크롤링 완료
26번째 페이지 크롤링 완료
27번째 페이지 크롤링 완료
28번째 페이지 크롤링 완료
29번째 페이지 크롤링 완료
30번째 페이지 크롤링 완료
31번째 페이지 크롤링 완료
32번째 페이지 크롤링 완료
33번째 페이지 크롤링 완료
34번째 페이지 크롤링 완료
35번째 페이지 크롤링 완료
36번째 페이지 크롤링 완료
37번째 페이지 크롤링 완료
38번째 페이지 크롤링 완료
39번째 페이지 크롤링 완료
40번째 페이지 크롤링 완료
41번째 페이지 크롤링 완료
42번째 페이지 크롤링 완료
43번째 페이지 크롤링 완료
44번째 페이지 크롤링 완료
45번째 페이지 크롤링 완료
46번째 페이지 크롤링 완료
47번째 페이지 크롤링 완료
48번째 페이지 크롤링 완료
49번째 페이지 크롤링 완료
50번째 페이지 크롤링 완료
51번째 페이지 크롤링 완료
52번째 페이지 크롤링 완료
53번째 페이지 크롤링 완료
54번째 페이지 크롤링 완료
55번째 페이지 크롤링 완료
56번째 페이지 크롤링 완료
57번째 페이지 크롤링 완료
58번째 페이지 크롤링 완료
59번째 페이지 크롤링 완료
60번째 페이지 크롤링 완료
61번째 페이지 크롤링 완료
62번째 페이지 크롤링 완료
63번째 페이지 크롤링 완료
64번째 페이지 크롤링 완료
65번째 페이지 크롤링 완료
66번째 페이지 크롤링 완료
67번째 페이지 크롤링 완료
68번째 페이지 크롤링 완료
69번째 페이지 크롤링 완료
70번째 페이지 크롤링 완료
71번째 페이지 크롤링 완료
72번째 페이지 크롤링 완료
73번째 페이지 크롤링 완료
74번째 페이지 크롤링 완료
75번째 페이지 크롤링 완료
76번째 페이지 크롤링 완료
77번째 페이지 크롤링 완료
78번째 페이지 크롤링 완료
79번째 페이지 크롤링 완료
80번째 페이지 크롤링 완료
81번째 페이지 크롤링 완료
82번째 페이지 크롤링 완료
83번째 페이지 크롤링 완료
84번째 페이지 크롤링 완료
85번째 페이지 크롤링 완료
86번째 페이지 크롤링 완료
87번째 페이지 크롤링 완료
88번째 페이지 크롤링 완료
89번째 페이지 크롤링 완료
90번째 페이지 크롤링 완료
91번째 페이지 크롤링 완료
92번째 페이지 크롤링 완료
93번째 페이지 크롤링 완료
94번째 페이지 크롤링 완료
95번째 페이지 크롤링 완료
96번째 페이지 크롤링 완료
97번째 페이지 크롤링 완료
98번째 페이지 크롤링 완료
99번째 페이지 크롤링 완료
100번째 페이지 크롤링 완료
101번째 페이지 크롤링 완료
102번째 페이지 크롤링 완료
103번째 페이지 크롤링 완료
104번째 페이지 크롤링 완료
105번째 페이지 크롤링 완료
106번째 페이지 크롤링 완료
107번째 페이지 크롤링 완료
108번째 페이지 크롤링 완료
109번째 페이지 크롤링 완료
110번째 페이지 크롤링 완료
111번째 페이지 크롤링 완료
112번째 페이지 크롤링 완료
113번째 페이지 크롤링 완료
114번째 페이지 크롤링 완료
115번째 페이지 크롤링 완료
116번째 페이지 크롤링 완료
117번째 페이지 크롤링 완료
118번째 페이지 크롤링 완료
119번째 페이지 크롤링 완료
120번째 페이지 크롤링 완료
121번째 페이지 크롤링 완료
122번째 페이지 크롤링 완료
123번째 페이지 크롤링 완료
124번째 페이지 크롤링 완료
125번째 페이지 크롤링 완료
126번째 페이지 크롤링 완료
127번째 페이지 크롤링 완료
128번째 페이지 크롤링 완료
129번째 페이지 크롤링 완료
130번째 페이지 크롤링 완료
131번째 페이지 크롤링 완료
132번째 페이지 크롤링 완료
133번째 페이지 크롤링 완료
134번째 페이지 크롤링 완료
135번째 페이지 크롤링 완료
136번째 페이지 크롤링 완료
137번째 페이지 크롤링 완료
138번째 페이지 크롤링 완료
139번째 페이지 크롤링 완료
140번째 페이지 크롤링 완료
141번째 페이지 크롤링 완료
142번째 페이지 크롤링 완료
143번째 페이지 크롤링 완료
144번째 페이지 크롤링 완료
145번째 페이지 크롤링 완료
146번째 페이지 크롤링 완료
147번째 페이지 크롤링 완료
148번째 페이지 크롤링 완료
149번째 페이지 크롤링 완료
150번째 페이지 크롤링 완료
151번째 페이지 크롤링 완료
152번째 페이지 크롤링 완료
153번째 페이지 크롤링 완료
154번째 페이지 크롤링 완료
155번째 페이지 크롤링 완료
156번째 페이지 크롤링 완료
157번째 페이지 크롤링 완료
158번째 페이지 크롤링 완료
159번째 페이지 크롤링 완료
160번째 페이지 크롤링 완료
161번째 페이지 크롤링 완료
162번째 페이지 크롤링 완료
163번째 페이지 크롤링 완료
164번째 페이지 크롤링 완료
165번째 페이지 크롤링 완료
166번째 페이지 크롤링 완료
167번째 페이지 크롤링 완료
168번째 페이지 크롤링 완료
169번째 페이지 크롤링 완료
170번째 페이지 크롤링 완료
171번째 페이지 크롤링 완료
172번째 페이지 크롤링 완료
173번째 페이지 크롤링 완료
174번째 페이지 크롤링 완료
175번째 페이지 크롤링 완료
176번째 페이지 크롤링 완료
177번째 페이지 크롤링 완료
178번째 페이지 크롤링 완료
179번째 페이지 크롤링 완료
180번째 페이지 크롤링 완료
181번째 페이지 크롤링 완료
182번째 페이지 크롤링 완료
183번째 페이지 크롤링 완료
184번째 페이지 크롤링 완료
185번째 페이지 크롤링 완료
186번째 페이지 크롤링 완료
187번째 페이지 크롤링 완료
188번째 페이지 크롤링 완료
189번째 페이지 크롤링 완료
190번째 페이지 크롤링 완료
191번째 페이지 크롤링 완료
192번째 페이지 크롤링 완료
193번째 페이지 크롤링 완료
194번째 페이지 크롤링 완료
195번째 페이지 크롤링 완료
196번째 페이지 크롤링 완료
197번째 페이지 크롤링 완료
198번째 페이지 크롤링 완료
199번째 페이지 크롤링 완료
200번째 페이지 크롤링 완료
201번째 페이지 크롤링 완료
202번째 페이지 크롤링 완료
203번째 페이지 크롤링 완료
204번째 페이지 크롤링 완료
205번째 페이지 크롤링 완료
206번째 페이지 크롤링 완료
207번째 페이지 크롤링 완료
208번째 페이지 크롤링 완료
209번째 페이지 크롤링 완료
210번째 페이지 크롤링 완료
211번째 페이지 크롤링 완료
212번째 페이지 크롤링 완료
213번째 페이지 크롤링 완료
214번째 페이지 크롤링 완료
215번째 페이지 크롤링 완료
216번째 페이지 크롤링 완료
217번째 페이지 크롤링 완료
218번째 페이지 크롤링 완료
219번째 페이지 크롤링 완료
220번째 페이지 크롤링 완료
221번째 페이지 크롤링 완료
222번째 페이지 크롤링 완료
223번째 페이지 크롤링 완료
224번째 페이지 크롤링 완료
225번째 페이지 크롤링 완료
226번째 페이지 크롤링 완료
227번째 페이지 크롤링 완료
228번째 페이지 크롤링 완료
229번째 페이지 크롤링 완료
230번째 페이지 크롤링 완료
231번째 페이지 크롤링 완료
232번째 페이지 크롤링 완료
233번째 페이지 크롤링 완료
234번째 페이지 크롤링 완료
235번째 페이지 크롤링 완료
236번째 페이지 크롤링 완료
237번째 페이지 크롤링 완료
238번째 페이지 크롤링 완료
239번째 페이지 크롤링 완료
240번째 페이지 크롤링 완료
241번째 페이지 크롤링 완료
242번째 페이지 크롤링 완료
243번째 페이지 크롤링 완료
244번째 페이지 크롤링 완료
245번째 페이지 크롤링 완료
246번째 페이지 크롤링 완료
247번째 페이지 크롤링 완료
248번째 페이지 크롤링 완료
249번째 페이지 크롤링 완료
250번째 페이지 크롤링 완료
251번째 페이지 크롤링 완료
252번째 페이지 크롤링 완료
253번째 페이지 크롤링 완료
254번째 페이지 크롤링 완료
255번째 페이지 크롤링 완료
256번째 페이지 크롤링 완료
257번째 페이지 크롤링 완료
258번째 페이지 크롤링 완료
259번째 페이지 크롤링 완료
260번째 페이지 크롤링 완료
261번째 페이지 크롤링 완료
262번째 페이지 크롤링 완료
263번째 페이지 크롤링 완료
264번째 페이지 크롤링 완료
265번째 페이지 크롤링 완료
266번째 페이지 크롤링 완료
267번째 페이지 크롤링 완료
268번째 페이지 크롤링 완료
269번째 페이지 크롤링 완료
270번째 페이지 크롤링 완료
271번째 페이지 크롤링 완료
272번째 페이지 크롤링 완료
273번째 페이지 크롤링 완료
274번째 페이지 크롤링 완료
275번째 페이지 크롤링 완료
276번째 페이지 크롤링 완료
277번째 페이지 크롤링 완료
278번째 페이지 크롤링 완료
279번째 페이지 크롤링 완료
280번째 페이지 크롤링 완료
281번째 페이지 크롤링 완료
282번째 페이지 크롤링 완료
283번째 페이지 크롤링 완료
284번째 페이지 크롤링 완료
285번째 페이지 크롤링 완료
286번째 페이지 크롤링 완료
287번째 페이지 크롤링 완료
288번째 페이지 크롤링 완료
289번째 페이지 크롤링 완료
290번째 페이지 크롤링 완료
291번째 페이지 크롤링 완료
292번째 페이지 크롤링 완료
293번째 페이지 크롤링 완료
294번째 페이지 크롤링 완료
295번째 페이지 크롤링 완료
296번째 페이지 크롤링 완료
297번째 페이지 크롤링 완료
298번째 페이지 크롤링 완료
299번째 페이지 크롤링 완료
300번째 페이지 크롤링 완료
301번째 페이지 크롤링 완료
302번째 페이지 크롤링 완료
303번째 페이지 크롤링 완료
304번째 페이지 크롤링 완료
305번째 페이지 크롤링 완료
306번째 페이지 크롤링 완료
307번째 페이지 크롤링 완료
308번째 페이지 크롤링 완료
309번째 페이지 크롤링 완료
310번째 페이지 크롤링 완료
311번째 페이지 크롤링 완료
312번째 페이지 크롤링 완료
313번째 페이지 크롤링 완료
314번째 페이지 크롤링 완료
315번째 페이지 크롤링 완료
316번째 페이지 크롤링 완료
317번째 페이지 크롤링 완료
318번째 페이지 크롤링 완료
319번째 페이지 크롤링 완료
320번째 페이지 크롤링 완료
321번째 페이지 크롤링 완료
322번째 페이지 크롤링 완료
323번째 페이지 크롤링 완료
324번째 페이지 크롤링 완료
325번째 페이지 크롤링 완료
326번째 페이지 크롤링 완료
327번째 페이지 크롤링 완료
328번째 페이지 크롤링 완료
329번째 페이지 크롤링 완료
330번째 페이지 크롤링 완료
331번째 페이지 크롤링 완료
332번째 페이지 크롤링 완료
333번째 페이지 크롤링 완료
334번째 페이지 크롤링 완료
335번째 페이지 크롤링 완료
336번째 페이지 크롤링 완료
337번째 페이지 크롤링 완료
338번째 페이지 크롤링 완료
339번째 페이지 크롤링 완료
340번째 페이지 크롤링 완료
341번째 페이지 크롤링 완료
342번째 페이지 크롤링 완료
343번째 페이지 크롤링 완료
344번째 페이지 크롤링 완료
345번째 페이지 크롤링 완료
346번째 페이지 크롤링 완료
347번째 페이지 크롤링 완료
348번째 페이지 크롤링 완료
349번째 페이지 크롤링 완료
350번째 페이지 크롤링 완료
351번째 페이지 크롤링 완료
352번째 페이지 크롤링 완료
353번째 페이지 크롤링 완료
354번째 페이지 크롤링 완료
355번째 페이지 크롤링 완료
356번째 페이지 크롤링 완료
357번째 페이지 크롤링 완료
358번째 페이지 크롤링 완료
359번째 페이지 크롤링 완료
360번째 페이지 크롤링 완료
361번째 페이지 크롤링 완료
362번째 페이지 크롤링 완료
363번째 페이지 크롤링 완료
364번째 페이지 크롤링 완료
365번째 페이지 크롤링 완료
366번째 페이지 크롤링 완료
367번째 페이지 크롤링 완료
368번째 페이지 크롤링 완료
369번째 페이지 크롤링 완료
370번째 페이지 크롤링 완료
371번째 페이지 크롤링 완료
372번째 페이지 크롤링 완료
373번째 페이지 크롤링 완료
374번째 페이지 크롤링 완료
375번째 페이지 크롤링 완료
376번째 페이지 크롤링 완료
377번째 페이지 크롤링 완료
378번째 페이지 크롤링 완료
379번째 페이지 크롤링 완료
380번째 페이지 크롤링 완료
381번째 페이지 크롤링 완료
382번째 페이지 크롤링 완료
383번째 페이지 크롤링 완료
384번째 페이지 크롤링 완료
385번째 페이지 크롤링 완료
386번째 페이지 크롤링 완료
387번째 페이지 크롤링 완료
388번째 페이지 크롤링 완료
389번째 페이지 크롤링 완료
390번째 페이지 크롤링 완료
391번째 페이지 크롤링 완료
392번째 페이지 크롤링 완료
393번째 페이지 크롤링 완료
394번째 페이지 크롤링 완료
395번째 페이지 크롤링 완료
396번째 페이지 크롤링 완료
397번째 페이지 크롤링 완료
398번째 페이지 크롤링 완료
399번째 페이지 크롤링 완료
400번째 페이지 크롤링 완료
401번째 페이지 크롤링 완료
402번째 페이지 크롤링 완료
403번째 페이지 크롤링 완료
404번째 페이지 크롤링 완료
405번째 페이지 크롤링 완료
406번째 페이지 크롤링 완료
407번째 페이지 크롤링 완료
408번째 페이지 크롤링 완료
409번째 페이지 크롤링 완료
410번째 페이지 크롤링 완료
411번째 페이지 크롤링 완료
412번째 페이지 크롤링 완료
413번째 페이지 크롤링 완료
414번째 페이지 크롤링 완료
415번째 페이지 크롤링 완료
416번째 페이지 크롤링 완료
417번째 페이지 크롤링 완료
418번째 페이지 크롤링 완료
419번째 페이지 크롤링 완료
420번째 페이지 크롤링 완료
421번째 페이지 크롤링 완료
422번째 페이지 크롤링 완료
423번째 페이지 크롤링 완료
424번째 페이지 크롤링 완료
425번째 페이지 크롤링 완료
426번째 페이지 크롤링 완료
427번째 페이지 크롤링 완료
428번째 페이지 크롤링 완료
429번째 페이지 크롤링 완료
430번째 페이지 크롤링 완료
431번째 페이지 크롤링 완료
432번째 페이지 크롤링 완료
433번째 페이지 크롤링 완료
434번째 페이지 크롤링 완료
435번째 페이지 크롤링 완료
436번째 페이지 크롤링 완료
437번째 페이지 크롤링 완료
438번째 페이지 크롤링 완료
439번째 페이지 크롤링 완료
440번째 페이지 크롤링 완료
441번째 페이지 크롤링 완료
442번째 페이지 크롤링 완료
443번째 페이지 크롤링 완료
444번째 페이지 크롤링 완료
445번째 페이지 크롤링 완료
446번째 페이지 크롤링 완료
447번째 페이지 크롤링 완료
448번째 페이지 크롤링 완료
449번째 페이지 크롤링 완료
450번째 페이지 크롤링 완료
451번째 페이지 크롤링 완료
452번째 페이지 크롤링 완료
453번째 페이지 크롤링 완료
454번째 페이지 크롤링 완료
455번째 페이지 크롤링 완료
456번째 페이지 크롤링 완료
457번째 페이지 크롤링 완료
458번째 페이지 크롤링 완료
459번째 페이지 크롤링 완료
460번째 페이지 크롤링 완료
461번째 페이지 크롤링 완료
462번째 페이지 크롤링 완료
463번째 페이지 크롤링 완료
464번째 페이지 크롤링 완료
465번째 페이지 크롤링 완료
466번째 페이지 크롤링 완료
467번째 페이지 크롤링 완료
468번째 페이지 크롤링 완료
469번째 페이지 크롤링 완료
470번째 페이지 크롤링 완료
471번째 페이지 크롤링 완료
472번째 페이지 크롤링 완료
473번째 페이지 크롤링 완료
474번째 페이지 크롤링 완료
475번째 페이지 크롤링 완료
476번째 페이지 크롤링 완료
477번째 페이지 크롤링 완료
478번째 페이지 크롤링 완료
479번째 페이지 크롤링 완료
480번째 페이지 크롤링 완료
481번째 페이지 크롤링 완료
482번째 페이지 크롤링 완료
483번째 페이지 크롤링 완료
484번째 페이지 크롤링 완료
485번째 페이지 크롤링 완료
486번째 페이지 크롤링 완료
487번째 페이지 크롤링 완료
488번째 페이지 크롤링 완료
489번째 페이지 크롤링 완료

490번째 페이지 크롤링 완료
491번째 페이지 크롤링 완료
492번째 페이지 크롤링 완료
493번째 페이지 크롤링 완료
494번째 페이지 크롤링 완료
495번째 페이지 크롤링 완료
496번째 페이지 크롤링 완료
497번째 페이지 크롤링 완료
498번째 페이지 크롤링 완료
499번째 페이지 크롤링 완료
500번째 페이지 크롤링 완료
501번째 페이지 크롤링 완료
502번째 페이지 크롤링 완료
503번째 페이지 크롤링 완료
504번째 페이지 크롤링 완료
505번째 페이지 크롤링 완료
506번째 페이지 크롤링 완료
507번째 페이지 크롤링 완료
508번째 페이지 크롤링 완료
509번째 페이지 크롤링 완료
510번째 페이지 크롤링 완료
511번째 페이지 크롤링 완료
512번째 페이지 크롤링 완료
513번째 페이지 크롤링 완료
514번째 페이지 크롤링 완료
515번째 페이지 크롤링 완료
516번째 페이지 크롤링 완료
517번째 페이지 크롤링 완료
518번째 페이지 크롤링 완료
519번째 페이지 크롤링 완료
520번째 페이지 크롤링 완료
521번째 페이지 크롤링 완료
522번째 페이지 크롤링 완료
523번째 페이지 크롤링 완료
524번째 페이지 크롤링 완료
525번째 페이지 크롤링 완료
526번째 페이지 크롤링 완료
527번째 페이지 크롤링 완료
528번째 페이지 크롤링 완료
529번째 페이지 크롤링 완료
530번째 페이지 크롤링 완료
531번째 페이지 크롤링 완료
532번째 페이지 크롤링 완료
533번째 페이지 크롤링 완료
534번째 페이지 크롤링 완료
535번째 페이지 크롤링 완료
536번째 페이지 크롤링 완료
537번째 페이지 크롤링 완료
538번째 페이지 크롤링 완료
539번째 페이지 크롤링 완료
540번째 페이지 크롤링 완료
541번째 페이지 크롤링 완료
542번째 페이지 크롤링 완료
543번째 페이지 크롤링 완료
543번째 페이지에서 크롤링 종료

            KPI200      거래량
2006-01-03  178.81  4161549
2006-01-04  179.91  5360812
2006-01-05  178.82  5522148
2006-01-06  180.87  4609858
2006-01-09  180.30  4641279
2006-01-10  178.98  4490698
2006-01-11  178.67  3878272
2006-01-12  179.65  4299763
2006-01-13  181.71  4162732
2006-01-16  182.39  4003185
2006-01-17  178.27  4245124
2006-01-18  173.81  5405430
2006-01-19  174.93  4017531
2006-01-20  170.60  4551399
2006-01-23  168.04  4595507
2006-01-24  171.79  4722143
2006-01-25  173.52  4853085
2006-01-26  174.71  4015803
2006-01-27  178.64  4289859
2006-01-31  180.65  4026822
2006-02-01  178.07  4242920
2006-02-02  177.92  4097390
2006-02-03  172.67  4047059
2006-02-06  173.66  3867241
2006-02-07  172.39  3203819
2006-02-08  169.44  3474910
2006-02-09  170.93  3481340
2006-02-10  172.68  3488863
2006-02-13  170.61  3143226
2006-02-14  171.65  2899291
...            ...      ...
2019-01-23  273.87  3322558
2019-01-24  276.61  4069123
2019-01-25  281.67  4956287
2019-01-28  281.64  4326570
2019-01-29  283.00  4131855
2019-01-30  286.62  4871048
2019-01-31  285.89  5878068
2019-02-01  285.79  4725369
2019-02-07  285.65  4244171
2019-02-08  281.49  3927493
2019-02-11  282.10  3579370
2019-02-12  283.69  4162823
2019-02-13  284.97  3887508
2019-02-14  288.68  4743123
2019-02-15  283.98  3547240
2019-02-18  285.90  3341225
2019-02-19  284.91  3064526
2019-02-20  288.40  4294950
2019-02-21  288.41  3915114
2019-02-22  288.74  3038312
2019-02-25  289.00  3386703
2019-02-26  287.89  3573682
2019-02-27  288.76  3552276
2019-02-28  283.80  6012739
2019-03-04  282.51  4881742
2019-03-05  280.45  3661228
2019-03-06  279.85  3486115
2019-03-07  278.87  3572145
2019-03-08  274.84  3258854
2019-03-11  275.06  3004400

[3258 rows x 2 columns]

In [ ]:
def get_a(until_date='1995-12-27'):
    
    path = 'd:\\a.xlsx'
        
    url = 'http://finance.naver.com/sise/investorDealTrendDay.nhn?bizdate=2020601&sosok=&page='
    Data = pd.DataFrame(columns = ['개인','외국인','기관'])
    date_list = []
    
    # 값을 받을 사전
    dictionary = {'개인': [],'외국인': [],'기관':[]}

    # dictionary key 인덱싱을 위한 리스트
    name_list = ['개인','외국인','기관']

    # count mask
    #mask = [0,1,2.3]
    mask = [0,1,2,3]
    
    for i in range(1,700):
        source = urlopen(url+ str(i)).read()
        source = BeautifulSoup(source,'lxml')

        body = source.find('body')
        trs = body.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            #print(tds)
            count = 0
            for td in tds:
                if not td.text.strip ==0:
                    if count == 0:
                        date_ = td.text.strip().replace('.','-')
                                
                        if not date_ in date_list :
                            date_list.append(date_)
                                    
                        #마지막 페이지인 경우
                        else:
                            print(str(i-1) + '번째 페이지에서 크롤링 종료')
                            date_list.pop(-1)
                            df = pd.DataFrame(dictionary,index = date_list)
                            df = df.sort_index()
                            #df.거래량 = df.거래량.str.replace(',','')
                            df.to_excel(path, encoding='utf-8')
                                
                            return df

                    elif count in mask:
                        #print("count={}".format(count))
                        temp = int(count-1)
                        #print("temp={}".format(temp))
                        dictionary[name_list[temp]].append(td.text.strip())
                        
                count += 1
                        
get_a()